@baseURL = http://localhost:3000

# @name verifyParticipantAndRegisterEvent
POST {{baseURL}}/attendees/register-event/:EventID(format: UUID)
Authorization: {{token}}
Content-Type: application/json

###

# @name find-unique-registration
GET {{baseURL}}/attendees/find-events-registration/:EventID(format: UUID)
Authorization: {{token}}
Content-Type: application/json

###

# @name find-all
GET {{baseURL}}/attendees/:PArticipantID(format: UUID)
Authorization: {{token}}
Content-Type: application/json

###

# @name find-unique-registration
DELETE  {{baseURL}}/attendees/cancel-registration/:EventID(format: UUID)
Authorization: {{token}}
Content-Type: application/json