@baseURL = http://localhost:3000

# @name create-comment
POST {{baseURL}}/comments/:EventID(format: UUID)
Authorization: {{token}}
Content-Type: application/json

{
    "commentText": "Esse evento foi bom demais eu super recomendo."
}

###

# @name update-comment
PATCH {{baseURL}}/comments/:CommentID(format: UUID)
Authorization: {{token}}
Content-Type: application/json

{
    "commentText": "Evento ruim de mais."
}

###

# @name delete-comment
DELETE  {{baseURL}}/comments/delete/:CommentID(format: UUID)
Authorization: {{token}}
Content-Type: application/json