@baseURL = http://localhost:3000

# @name create-comment
POST {{baseURL}}/comments/f0346839-60d5-4bb2-993f-38e70c5c4e7f
Authorization: {{token}}
Content-Type: application/json

{
    "commentText": "Esse evento foi bom demais eu super recomendo."
}

###

# @name update-comment
PATCH {{baseURL}}/comments/50830996-ecee-4086-9abb-d0506d46c49e
Authorization: {{token}}
Content-Type: application/json

{
    "commentText": "Evento ruim de mais."
}

###

# @name delete-comment
DELETE  {{baseURL}}/comments/delete/50830996-ecee-4086-9abb-d0506d46c49e
Authorization: {{token}}
Content-Type: application/json