@baseURL = http://localhost:3000

# @name update-participant
PATCH {{baseURL}}/participants/143157b0-0dbf-46a0-b78e-4b856d0b273e
Content-Type: application/json

{
    "bio": "Sou um participante desta API",
    "website": "juanbarcelos1@gmail.com"
}