@baseURL = http://localhost:3000

# @name create-users
POST {{baseURL}}/users
Content-Type: application/json

{
    "userName":"Beatriz",
    "email":"Beatriz@gmail.com",
    "password":"032194Jb",
    "fullName":"Beatriz",
    "role": "attendees"
}

###

# @name update-user-organizer-profile
PATCH  {{baseURL}}/users/profile/764e130e-fac6-4327-aeb3-9e6223457d37
Content-Type: application/json

{
    "userName":"AdrieleBarcelos",
    "email":"adriele@gmail.com",
    "fullName":"Adriele Santos Barcelos",
    "bio": "Sou esposa do dono desta API",
    "website": "www.adrielebarcelos.com.br",
    "organizationName": "Nova Vida"
}

###

# @name update-user-participant-profile
PATCH  {{baseURL}}/users/profile/143157b0-0dbf-46a0-b78e-4b856d0b273e
Content-Type: application/json

{
    "userName":"Juan_Barcelos",
    "email":"juan@gmail.com",
    "fullName":"Juna Barcelos Update",
    "bio": "Esta sendo dificil fazer esta API",
    "website": "www.juan.com.br",
    "organizationName": ""
}

###

# @name delete-user-account
DELETE {{baseURL}}/users/delete/account/2f5b268d-e330-42c6-9172-b1e87319618e
Content-Type: application/json

{
    "email":"Beatriz@gmail.com"
}