@baseURL = http://localhost:3000

# @name create-users
POST {{baseURL}}/users
Content-Type: application/json

{
    "userName":"Admim Participant",
    "email":"admim-participant@gmail.com",
    "password":"00000Aa",
    "fullName":"admim Participant",
    "role": "attendees"
}

###

# @name update-user-organizer-profile
PATCH  {{baseURL}}/users/profile
Authorization: {{token}}
Content-Type: application/json

{
    "userName":"AdminParticipantUpdate",
    "email":"admim-participant@gmail.com",
    "fullName":"Admin Participant Update",
    "bio": "Sou a API-UPDATE",
    "website": "www.update.com.br",
    "organizationName": "Lanches"
}

###

# @name update-user-participant-profile
PATCH  {{baseURL}}/users/profile
Authorization: {{token}}
Content-Type: application/json

{
    "userName":"AdminParticipantUpdate",
    "email":"admim-participant@gmail.com",
    "fullName":"Admin Participant Update",
    "bio": "Sou a API-UPDATE",
    "website": "www.update.com.br",
}

###

# @name delete-user-account
DELETE {{baseURL}}/users/delete/account
Authorization: {{token}}
Content-Type: application/json

{
    "email":""
}